name: Testing and Analysis

on: 
  workflow_call:
    inputs:
      runs_on:
        required: true
        type: string

jobs:
  run:
    runs-on: ${{ inputs.runs_on }}
    environment: Development

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Cache Flutter dependencies
      uses: actions/cache@v3.2.4
      with:
        path: /opt/hostedtoolcache/flutter
        key: ${{ runner.OS }}-flutter-install-cache-${{ env.FLUTTER_VERSION }}
    
    - name: Set up Flutter
      if: ${{ inputs.runs_on != 'self-hosted' }}
      uses: subosito/flutter-action@v2
      with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

    - name: Install project dependencies
      run: |
        flutter pub get

    - name: Check formatting
      run: flutter format --set-exit-if-changed .

    - name: Run static analysis
      run: flutter analyze .

    - name: Run tests
      run: |
        flutter test --machine test
