name: Testing and Analysis

on:
  workflow_call:
    inputs:
      runs_on:
        required: true
        type: string

jobs:
  run:
    runs-on: ${{ inputs.runs_on }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Flutter dependencies
        uses: actions/cache@v3.2.4
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache

      - name: Set up Flutter
        if: ${{ inputs.runs_on != 'self-hosted' }}
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: |
          echo "---------------------------------------------------------------------"
          echo CACHE-PATH=${{ steps.flutter-action.outputs.CACHE-PATH }}
          echo CACHE-KEY=${{ steps.flutter-action.outputs.CACHE-KEY }}
          echo CHANNEL=${{ steps.flutter-action.outputs.CHANNEL }}
          echo VERSION=${{ steps.flutter-action.outputs.VERSION }}
          echo ARCHITECTURE=${{ steps.flutter-action.outputs.ARCHITECTURE }}
          echo "---------------------------------------------------------------------"
        shell: bash

      - name: Install project dependencies
        run: |
          flutter pub get

      - name: Check formatting
        run: flutter format --set-exit-if-changed .

      - name: Run static analysis
        run: flutter analyze .

      - name: Run tests
        run: |
          flutter test --machine test
